# Data Preprocessing

Data preprocessing prepares raw data for machine learning.

Common steps:

- Handling missing values
- Removing duplicates
- Detecting outliers
- Encoding categorical features
- Feature scaling
- Data type correction


In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [25, 30, np.nan, 40, 35],
    "Salary": [30000, 50000, 45000, np.nan, 70000],
    "City": ["Bangalore", "Delhi", "Bangalore", "Mumbai", "Delhi"]
})

df


,Age,Salary,City
0,25.0,30000.0,Bangalore
1,30.0,50000.0,Delhi
2,NaN,45000.0,Bangalore
3,40.0,NaN,Mumbai
4,35.0,70000.0,Delhi


## Check Missing Values

In [2]:
print(df.isnull().sum())


Age       1
Salary    1
City      0
dtype: int64


## Numerical Imputation

In [3]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df


,Age,Salary,City
0,25.0,30000.0,Bangalore
1,30.0,50000.0,Delhi
2,32.5,45000.0,Bangalore
3,40.0,47500.0,Mumbai
4,35.0,70000.0,Delhi


## Encoding Categorical Variables

Common encoders:

- `OneHotEncoder` — nominal categories
- `OrdinalEncoder` — ordered categories
- `LabelEncoder` — usually used for target labels


In [4]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded = encoder.fit_transform(df[["City"]])

print(encoder.get_feature_names_out(["City"]))
print(encoded)


['City_Bangalore' 'City_Delhi' 'City_Mumbai']
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


## Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_salary = scaler.fit_transform(df[["Salary"]])

print(scaled_salary)


[[-1.4446073 ]
 [ 0.11713032]
 [-0.27330408]
 [-0.07808688]
 [ 1.67886794]]
