# Numpy

#### Numpy is a fundamental Package for scientific computing in python. It is a Pthon library that provides a multi dimensional Array object and various derived objects such as Masked Arrays, Matrices and an assortment of routines for fast operations on Array include Mathematical, logical, Shape manipulation, Sorting, Selecting, I/O, Descrete Fourier Transform, basic Linear Algebra, Stastical Operations, Random simulation, etc

## Numpy Arrays Vs Python Sequences

#### Numpy Array have a fixed size at creation, unlike Python lists which row dynamically.Changing the size of an n-dim array will create a new array and delete the original.

### The element in Numpy array are req to have same datatype and thus will be of same size in memory.

### Numpy array facilitates advanced Mathematical and other types of operation on large number of data. typically, such operation are executed more efficently with less code than is possible using python's built in sequences.

In [3]:
import numpy as np

np.__version__

'2.5.1'

In [6]:
numpy_array = np.array([1, 2, 3, 4, 5])

print(numpy_array)
type(numpy_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
TwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
threeDArray = np.array([[[1,2],[3, 4]], [[10, 20], [30, 40]],[[28, 63],[34, 49]]])
threeDArray

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]],

       [[28, 63],
        [34, 49]]])

## dtype parameter ---> help us out with deciding about size of data we are going to store inside our array

In [15]:
np.array([1, 2, 3, 4, 5], dtype=np.int32) # memory size of 4 bytes per element

np.array([11, 21, 32, 4, 53], dtype=np.int64) # memory size of 8 bytes per element

array([11, 21, 32,  4, 53])

## arange() ---> It helps us out with providing the values over a certain range

In [18]:
np.arange(10) # 1D array with values from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5, 25) # 1D array with values from 5 to 24

np.arange(5, 25, 2) # 1D array with values from 5 to 24 with step size of 2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [21]:
arange_data = np.arange(1, 17)

arange_data.reshape(4, 4) # Reshape the 1D array into a 2D array with 4 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
np.ones((3, 3)) # Create a 2D array of shape (3, 3) filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((2, 4)) # Create a 2D array of shape (2, 4) filled with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3, 3)) # Create a 2D array of shape (3, 3) filled with random values between 0 and 1

array([[0.19898026, 0.02771812, 0.61615883],
       [0.45414115, 0.3859165 , 0.69058203],
       [0.69150887, 0.89056491, 0.35989326]])

In [25]:
np.identity(4) # Create a 2D identity matrix of shape (4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.linspace(0, 1, 5) # Create a 1D array of 5 evenly spaced values between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])