In [1]:
import numpy as np

array_data = np.array(np.random.randint(30, 77, size=(4,4)))
print(array_data)

[[73 76 56 51]
 [69 69 46 32]
 [30 30 60 53]
 [51 61 62 50]]


# Statistical Functions

In [4]:
# mean
print("Mean of the array:", np.mean(array_data))
print("-" * 40)

# median
print("Median of the array:", np.median(array_data))
print("-" * 40)

# standard deviation
print("Standard Deviation of the array:", np.std(array_data))
print("-" * 40)

# variance
print("Variance of the array:", np.var(array_data))
print("-" * 40)

Mean of the array: 54.3125
----------------------------------------
Median of the array: 54.5
----------------------------------------
Standard Deviation of the array: 14.101058249294626
----------------------------------------
Variance of the array: 198.83984375
----------------------------------------


# log and exponential functions

In [5]:
arr = np.array([1, 2, 3])

# natural logarithm
print("Natural Logarithm of the array:", np.log(arr))
print("-" * 40)

# Base 10 logarithm
print("Base 10 Logarithm of the array:", np.log10(arr))
print("-" * 40)

#Base-2 logarithm
print("Base 2 Logarithm of the array:", np.log2(arr))
print("-" * 40)

#exponential
print("Exponential of the array:", np.exp(arr))
print("-" * 40)

Natural Logarithm of the array: [0.         0.69314718 1.09861229]
----------------------------------------
Base 10 Logarithm of the array: [0.         0.30103    0.47712125]
----------------------------------------
Base 2 Logarithm of the array: [0.        1.        1.5849625]
----------------------------------------
Exponential of the array: [ 2.71828183  7.3890561  20.08553692]
----------------------------------------
