In [6]:
import numpy as np

# Mathematical operation in numpy

In [7]:
arr = np.random.random((3, 3))* 100

In [8]:
arr = np.round(arr)

arr

array([[55., 20.,  9.],
       [83., 51., 95.],
       [19., 70., 12.]])

In [11]:
# Basic Arithmetic Functions

# addition
arr = np.add(arr, 10)
print(arr)
print("-" * 40)

# subtraction
arr = np.subtract(arr, 10)
print(arr)
print("-" * 40)

# multiplication
arr = np.multiply(arr, 10)
print(arr)
print("-" * 40)

# division
arr = np.divide(arr, 10)
print(arr)
print("-" * 40)

[[ 65.  30.  19.]
 [ 93.  61. 105.]
 [ 29.  80.  22.]]
----------------------------------------
[[55. 20.  9.]
 [83. 51. 95.]
 [19. 70. 12.]]
----------------------------------------
[[550. 200.  90.]
 [830. 510. 950.]
 [190. 700. 120.]]
----------------------------------------
[[55. 20.  9.]
 [83. 51. 95.]
 [19. 70. 12.]]
----------------------------------------


In [14]:
# vector operations
arr_1 = np.arange(1, 17).reshape(4, 4)
arr_2 = np.arange(17, 33).reshape(4, 4)

print(arr_1 + arr_2)
print("-" * 40)

print(arr_2 - arr_1)
print("-" * 40)


[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]
----------------------------------------
[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
----------------------------------------


In [ ]:
# axis in numpy is used to specify the dimension along which an operation should be performed.
# axis=0 --> rows (vertical direction), and axis=1 --> columns (horizontal direction).

array_data = np.array(np.random.randint(30, 77, size=(4,4)))
print(array_data)
print("-" * 40)

print(np.max(array_data))
print("Max along axis 0 (rows):" , np.max(array_data, axis=0))
print("Max along axis 1 (columns):" , np.max(array_data, axis=1))

[[54 49 66 47]
 [72 33 58 41]
 [64 76 37 46]
 [67 41 40 64]]
----------------------------------------
76
Max along axis 0 (rows): [72 76 66 64]
Max along axis 1 (columns): [66 72 76 67]


In [22]:
print(np.min(array_data))
print("Min along axis 0 (rows):" , np.min(array_data, axis=0))
print("Min along axis 1 (columns):" , np.min(array_data, axis=1))
print("-" * 40)

print(np.sum(array_data))



33
Min along axis 0 (rows): [54 33 37 41]
Min along axis 1 (columns): [47 33 37 40]
----------------------------------------
855
